version: "3"
services:
  discord-bot:
    restart: always
    build: .
    environment: 
      DISCORD_BOT_TOKEN: "yourtoken"
      GOOGLE_APPLICATION_CREDENTIALS: "/app/sa-key.json"
    volumes:
      - .:/app:rw
